specVersion: 0.2.0
name: validator-threshold
version: 0.2.0
description: >-
  This subquery indexes bond,reward and slash of each block, summarize total
  earning of an account
repository: https://github.com/subquery/subql-examples
schema:
  file: ./schema.graphql
network:
  genesisHash: '0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3'
  endpoint: wss://polkadot.api.onfinality.io/public-ws
  dictionary: https://api.subquery.network/sq/subquery/dictionary-polkadot
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/EventHandler
          filter:
            module: session
            method: NewSession
